"""Self-contained reimplementation of upstream gazelle() without an @gazelle dep.

Divergences: always passes -bzlmod; narrower command/mode values; expands
$(location)/$(rootpath) tokens in env values (upstream does not); `bazel run`
only — TEST_WORKSPACE handling is not emitted, so `bazel test` is unsupported.
"""

load("@bazel_skylib//lib:shell.bzl", "shell")

# Keep in sync with the same-named lists in //runner/rules.bzl.
_VALID_COMMANDS = ["update", "fix"]
_VALID_MODES = ["fix", "diff"]

# Copied from https://github.com/bazel-contrib/rules_shell/blob/v0.8.0/shell/runfiles/runfiles.bash#L70-L80
_RUNFILES_INIT = """\
# --- begin runfiles.bash initialization v3 ---
# Copy-pasted from the Bazel Bash runfiles library v3.
set -uo pipefail; set +e; f=bazel_tools/tools/bash/runfiles/runfiles.bash
# shellcheck disable=SC1090
source "${RUNFILES_DIR:-/dev/null}/$f" 2>/dev/null || \\
  source "$(grep -sm1 "^$f " "${RUNFILES_MANIFEST_FILE:-/dev/null}" | cut -f2- -d' ')" 2>/dev/null || \\
  source "$0.runfiles/$f" 2>/dev/null || \\
  source "$(grep -sm1 "^$f " "$0.runfiles_manifest" | cut -f2- -d' ')" 2>/dev/null || \\
  source "$(grep -sm1 "^$f " "$0.exe.runfiles_manifest" | cut -f2- -d' ')" 2>/dev/null || \\
  { echo>&2 "ERROR: cannot find $f"; exit 1; }; f=; set -e
# --- end runfiles.bash initialization v3 ---"""

# Copied from https://github.com/bazel-contrib/bazel-gazelle/blob/v0.50.0/def.bzl
def _rlocation_path(ctx, file):
    if file.short_path.startswith("../"):
        return file.short_path[3:]
    return ctx.workspace_name + "/" + file.short_path

# Copied from https://github.com/bazel-contrib/bazel-gazelle/blob/v0.50.0/def.bzl
def _valid_env_variable_name(name):
    if not name:
        return False
    for i, c in enumerate(name.elems()):
        if c.isalpha() or c == "_" or (i > 0 and c.isdigit()):
            continue
        return False
    return True

def _aspect_gazelle_runner_impl(ctx):
    toolchain = ctx.toolchains["//toolchain:type"]
    binary = toolchain.gazelle_info.binary
    gazelle_path = _rlocation_path(ctx, binary)

    env_lines = []
    for k, v in ctx.attr.env.items():
        if not _valid_env_variable_name(k):
            fail("Invalid environment variable name: '%s'" % k)
        env_lines.append("export %s=%s" % (k, shell.quote(ctx.expand_location(v, ctx.attr.data))))

    # Resolve runfile paths into shell variables so the exec line stays
    # readable and quoting is centralised in one spot per path.
    setup_lines = ['gazelle_bin="$(rlocation %s)"' % shell.quote(gazelle_path)]

    # Defaults are spliced ahead of "$@" so that first-match flag lookups in
    # the binary resolve to them rather than to any user-supplied duplicates.
    exec_parts = ['"$gazelle_bin"', ctx.attr.command, "-bzlmod", "-mode", ctx.attr.mode]
    if ctx.file.repo_config:
        repo_config_path = _rlocation_path(ctx, ctx.file.repo_config)
        setup_lines.append('repo_config="$(rlocation %s)"' % shell.quote(repo_config_path))
        exec_parts.append('"-repo_config=$repo_config"')
    exec_parts += [shell.quote(ctx.expand_location(a, ctx.attr.data)) for a in ctx.attr.extra_args]
    exec_parts.append('"$@"')

    # Runfiles init leaves us with `set -euo pipefail` already enabled.
    content = "\n".join([
        "#!/usr/bin/env bash",
        "# Generated by %s" % ctx.label,
        "",
        _RUNFILES_INIT,
        "",
    ] + env_lines + [
        "",
        "runfiles_export_envvars",
    ] + setup_lines + [
        "",
        'if [ -z "${BUILD_WORKSPACE_DIRECTORY-}" ]; then',
        '  echo "error: BUILD_WORKSPACE_DIRECTORY not set" >&2',
        "  exit 1",
        "fi",
        "",
        " ".join(exec_parts),
        "",
    ])

    out = ctx.actions.declare_file(ctx.label.name + ".sh")
    ctx.actions.write(output = out, content = content, is_executable = True)

    runfile_files = [binary] + ctx.files.data
    transitive_runfiles = [d[DefaultInfo].default_runfiles for d in ctx.attr.data]
    transitive_runfiles.append(ctx.attr._runfiles_lib[DefaultInfo].default_runfiles)
    if ctx.file.repo_config:
        runfile_files.append(ctx.file.repo_config)
        transitive_runfiles.append(ctx.attr.repo_config[DefaultInfo].default_runfiles)
    runfiles = ctx.runfiles(files = runfile_files).merge_all(transitive_runfiles)

    return [DefaultInfo(
        files = depset([out]),
        runfiles = runfiles,
        executable = out,
    )]

aspect_gazelle_runner = rule(
    implementation = _aspect_gazelle_runner_impl,
    executable = True,
    toolchains = ["//toolchain:type"],
    attrs = {
        "command": attr.string(default = "update", values = _VALID_COMMANDS),
        "mode": attr.string(default = "fix", values = _VALID_MODES),
        "extra_args": attr.string_list(),
        "data": attr.label_list(allow_files = True),
        "env": attr.string_dict(),
        "repo_config": attr.label(allow_single_file = True),
        "_runfiles_lib": attr.label(default = "@bazel_tools//tools/bash/runfiles"),
    },
)
