// Subpath import of a file generated by another Bazel package.
import { subId } from '#sub';
// Subpath import mapped to an external package.
import { otherId } from '#ext';
// Conditional subpath import mapping conditions to separate directories.
import { condId } from '#cond';
// Subpath import matching a '*' pattern.
import { internalId } from '#internal/util';

export const id = () => subId() + otherId() + condId() + internalId();
