# See https://docs.aspect.build/workflows/configuration/tasks
workspaces:
  .:
    icon: deer
  language/js:
    tasks:
      - buildifier:
          without: true
  language/kotlin:
    tasks:
      - buildifier:
          without: true
  language/orion:
    tasks:
      - buildifier:
          without: true
  runner:
    tasks:
      - buildifier:
          without: true
tasks:
  - buildifier:
  - gazelle:
  - test:
  # See https://docs.aspect.build/v/workflows/config
  # TODO: add windows and other targets
  - build:
      name: linux_amd64
      targets:
        - //:gazelle_prebuilt_bin
      bazel:
        flags:
          - --platforms=@rules_go//go/toolchain:linux_amd64_cgo
  - build:
      name: linux_arm64
      targets:
        - //:gazelle_prebuilt_bin
      bazel:
        flags:
          - --platforms=@rules_go//go/toolchain:linux_arm64_cgo
  - build:
      name: darwin_arm64
      targets:
        - //:gazelle_prebuilt_bin
      bazel:
        flags:
          - --platforms=@rules_go//go/toolchain:darwin_arm64_cgo
notifications:
  github: {}
