// Subpath import of a file generated by another Bazel package.
import { subId } from '#sub';
// Subpath import mapped to an external package.
import { otherId } from '#ext';
// Subpath import matching a '*' pattern.
import { internalId } from '#internal/util';
// Odd alias for a dependency reached ONLY via a package.json 'imports' entry.
import { dbId } from '#~db';

export const id = () => subId() + otherId() + internalId() + dbId();
