// Self-reference to an exports subpath generated by another Bazel package.
import { subId } from '@lib/pkg/sub';
// Self-reference matching a '*' exports pattern.
import { featId } from '@lib/pkg/feat/x';

export const id = () => subId() + featId();
