package gazelle

import (
	"errors"
	"fmt"
	"iter"
	"path"
	"strings"

	common "github.com/aspect-build/aspect-gazelle/common"
	BazelLog "github.com/aspect-build/aspect-gazelle/common/logger"
	plugin "github.com/aspect-build/aspect-gazelle/language/orion/plugin"
	"github.com/bazelbuild/bazel-gazelle/config"
	"github.com/bazelbuild/bazel-gazelle/label"
	gazelleLanguage "github.com/bazelbuild/bazel-gazelle/language"
	"github.com/bazelbuild/bazel-gazelle/repo"
	"github.com/bazelbuild/bazel-gazelle/resolve"
	"github.com/bazelbuild/bazel-gazelle/rule"
)

var _ resolve.Resolver = (*GazelleHost)(nil)

type ResolutionType = int

const (
	Resolution_Error ResolutionType = iota
	Resolution_None
	Resolution_NotFound
	Resolution_Label
	Resolution_Native
	Resolution_Override
)

func (*GazelleHost) Name() string {
	return GazelleLanguageName
}

func symbolToImportSpec(symbol plugin.Symbol) resolve.ImportSpec {
	return resolve.ImportSpec{
		Lang: symbol.Provider,
		Imp:  symbol.Id,
	}
}

const extGeneratedRules = "__starzelle_generated_rules"
const extGeneratedRulesPkg = "__starzelle_generated_rules_pkg"

func (re *GazelleHost) importsGenerateRules(cfg *BUILDConfig, c *config.Config, f *rule.File) gazelleLanguage.GenerateResult {
	regularFiles, err := common.GetSourceRegularFiles(f.Pkg)
	if err != nil {
		BazelLog.Fatalf("Error getting regular files for %s: %v", f.Pkg, err)
	}

	return re.generateRules(cfg, gazelleLanguage.GenerateArgs{
		File:   f,
		Rel:    f.Pkg,
		Dir:    path.Join(c.RepoRoot, f.Pkg),
		Config: c,

		// The RegularFiles are processed by the GazelleHost and passed to plugins.
		RegularFiles: regularFiles,
	})
}

// Determine what rule (r) outputs which can be imported.
func (re *GazelleHost) Imports(c *config.Config, r *rule.Rule, f *rule.File) []resolve.ImportSpec {
	BazelLog.Tracef("Imports(%s): //%s:%s", GazelleLanguageName, f.Pkg, r.Name())

	// This rule was generated by this gazelle extension.
	if declaration := r.PrivateAttr(targetDeclarationKey); declaration != nil {
		BazelLog.Debugf("Imports(%s): //%s:%s (generated %s)", GazelleLanguageName, f.Pkg, r.Name(), r.Kind())
		return symbolToImportSpecList(declaration.(plugin.TargetDeclaration).Symbols)
	}

	cfg := getBUILDConfig(c, f.Pkg)

	// Generation was done for this package, but this rule was not one of them.
	if cfg.generated {
		return nil
	}

	// Otherwise generation was not done for this package and must be manually invoked.
	//
	// With GazelleHost the Imports() functionality is provided at rule generation time, not
	// a separate Import-extraction phase.
	//
	// When running partial generations this means we must manually invoke GenerateRules() if it
	// was not invoked by gazelle as part of the partial run.
	if c.Exts[extGeneratedRulesPkg] != f.Pkg {
		BazelLog.Debugf("Imports.GenerateRules(%s): //%s", GazelleLanguageName, f.Pkg)
		c.Exts[extGeneratedRules] = re.importsGenerateRules(cfg, c, f)
		c.Exts[extGeneratedRulesPkg] = f.Pkg
	}

	// Find this rule in the host-generated rules
	genResult := c.Exts[extGeneratedRules].(gazelleLanguage.GenerateResult)
	for _, g := range genResult.Gen {
		if g.Kind() == r.Kind() && g.Name() == r.Name() {
			// TODO: what if the rule generation is different and not what is expected?
			// ... it is possible this directory is not being updated, and if it were updated
			// the result would be different.
			if declaration := g.PrivateAttr(targetDeclarationKey); declaration != nil {
				BazelLog.Debugf("Imports(%s): //%s:%s (not generated %s)", GazelleLanguageName, f.Pkg, g.Name(), g.Kind())
				return symbolToImportSpecList(declaration.(plugin.TargetDeclaration).Symbols)
			}
			break
		}
	}

	return nil
}

func symbolToImportSpecList(symbols []plugin.Symbol) []resolve.ImportSpec {
	res := make([]resolve.ImportSpec, 0, len(symbols))
	for _, s := range symbols {
		res = append(res, symbolToImportSpec(s))
	}
	return res
}

// Extra targets embedded within rules.
func (re *GazelleHost) Embeds(r *rule.Rule, f label.Label) []label.Label {
	return []label.Label{}
}

// Resolve the dependencies of a rule and apply them to the necessary rule attributes.
func (re *GazelleHost) Resolve(c *config.Config, ix *resolve.RuleIndex, rc *repo.RemoteCache, r *rule.Rule, importData interface{}, from label.Label) {
	BazelLog.Debugf("Resolve(%s): //%s:%s", GazelleLanguageName, from.Pkg, r.Name())

	pluginIdAttr := r.PrivateAttr(targetPluginKey)
	if pluginIdAttr == nil {
		return
	}

	pluginId := pluginIdAttr.(plugin.PluginId)

	// The import data is the imports per attribute
	attrValues := importData.(map[string]*attributeValue)

	for attr, attrValue := range attrValues {
		// The attribute is only constants (no imports) and needs no resolution.
		if len(attrValue.imports) == 0 {
			continue
		}

		importLabels, err := re.resolveImports(c, ix, pluginId, attrValue.imports, from)
		if err != nil {
			common.ImportErrorf(c, "Resolution Error: %v", err)
			continue
		}

		// NOTE: the attribute might have additional values added via # keep which gazelle will maintain
		// despite doing Set/DelAttr.

		if attrValue.singleton {
			switch importLabels.Size() {
			case 0:
				r.DelAttr(attr)
			case 1:
				for dep := range importLabels.Labels() {
					r.SetAttr(attr, dep)
				}
			default:
				common.GenerationErrorf(c, "Attribute %q on %s has resolved to multiple values: %v", attr, r.Name(), importLabels)
			}
		} else {
			value := attrValue.values
			for l := range importLabels.Labels() {
				value = append(value, l)
			}
			if len(value) > 0 {
				r.SetAttr(attr, value)
			} else {
				r.DelAttr(attr)
			}
		}
	}
}

func (re *GazelleHost) resolveImports(
	c *config.Config,
	ix *resolve.RuleIndex,
	pluginId plugin.PluginId,
	imports []plugin.TargetImport,
	from label.Label,
) (*common.LabelSet, error) {
	deps := common.NewLabelSet(from)

	var errs []error

	for _, imp := range imports {
		resolutionType, resolved, err := re.resolveImport(c, ix, pluginId, imp, from)
		if err != nil {
			return nil, err
		}

		if resolutionType == Resolution_NotFound {
			BazelLog.Debugf("import %q for target %v not found", imp.Id, from)

			if !imp.Optional {
				notFound := fmt.Errorf("Import %q (provider %q) from %q is an unknown dependency",
					imp.Id, imp.Provider, imp.From,
				)

				errs = append(errs, notFound)
				continue
			}
		}

		if resolutionType == Resolution_Native || resolutionType == Resolution_None {
			continue
		}

		for i := range resolved {
			deps.Add(&resolved[i])
		}
	}

	return deps, errors.Join(errs...)
}

func (host *GazelleHost) resolveImport(
	c *config.Config,
	ix *resolve.RuleIndex,
	pluginId plugin.PluginId,
	impt plugin.TargetImport,
	from label.Label,
) (ResolutionType, []label.Label, error) {
	// TODO: "native" imports
	// if IsNativeImport(impt.Imp) {
	// 	return Resolution_Native, nil, nil
	// }

	// One spec for ordinary imports, or one spec per pkg in the importer's chain (importing pkg through root)
	// for Ancestor imports. Each spec is tried against gazelle overrides and the rule index in turn.
	//
	// A `multiple` import unions matches from every source (the rule index and the symbol db) rather than
	// returning the first; `collected` accumulates them. `multiple` is mutually exclusive with `ancestor`,
	// so a `multiple` import always has exactly one spec.
	var collected []label.Label

	// matchedSelfOnly records that a `multiple` import found the Symbol but every match was a self-import.
	// Like a non-multiple self import, that resolves to nothing (Resolution_None) rather than erroring as
	// an unknown dependency.
	matchedSelfOnly := false

	for importSpec := range importSpecsToTry(impt, from.Pkg) {
		// A gazelle override replaces the entire resolution, including a multiple collection.
		if override, ok := resolve.FindRuleWithOverride(c, importSpec, GazelleLanguageName); ok {
			return Resolution_Label, []label.Label{override}, nil
		}

		matches := ix.FindRulesByImportWithConfig(c, importSpec, GazelleLanguageName)
		if len(matches) == 0 {
			continue
		}

		filtered := make([]label.Label, 0, len(matches))
		for _, match := range matches {
			if !match.IsSelfImport(from) {
				filtered = append(filtered, match.Label)
			}
		}

		if impt.Multiple {
			// Collect the rule-index matches, then fall through to also union symbol-db matches.
			collected = append(collected, filtered...)
			if len(filtered) == 0 {
				// Matches existed but were all self-imports.
				matchedSelfOnly = true
			}
			break
		}

		if len(filtered) > 1 {
			// Too many results and no way to choose - the plugin must disambiguate.
			return Resolution_Error, nil, fmt.Errorf(
				"Import %q from %q (%s) resolved to multiple targets (%s) - this must be fixed using the \"aspect:resolve\" directive",
				impt.Id, impt.From, pluginId, targetListFromResults(matches))
		}
		if len(filtered) == 1 {
			return Resolution_Label, filtered, nil
		}

		// All matches were self-imports: non-ancestor stops; ancestor walks up.
		if !impt.Ancestor {
			return Resolution_None, nil, nil
		}
	}

	// Look up symbols registered across plugins in the symbol db.
	if symbols := host.database.LookupSymbols(impt.Id); len(symbols) > 0 {
		// Symbols of the imported provider type.
		matched := make([]plugin.TargetSymbol, 0, len(symbols))
		for _, s := range symbols {
			if s.Provider == impt.Provider {
				matched = append(matched, s)
			}
		}

		if impt.Multiple {
			// A multiple import collects every same-provider symbol. It does NOT fall back
			// across provider types: an empty same-provider set means "none here", not
			// "every symbol of every provider".
			for _, s := range matched {
				collected = append(collected, symbolLabel(s))
			}
		} else {
			// A single import takes one symbol, preferring the imported provider type but
			// falling back to any provider type for cross-plugin imports (eg a "kt" import
			// satisfied by "java_info" symbols from the maven plugin).
			if len(matched) == 0 {
				matched = symbols
			}
			return Resolution_Label, []label.Label{symbolLabel(matched[0])}, nil
		}
	}

	if len(collected) > 0 {
		return Resolution_Label, collected, nil
	}

	// The Symbol was provided only by the importer itself: resolved, but nothing to add.
	if matchedSelfOnly {
		return Resolution_None, nil, nil
	}

	return Resolution_NotFound, nil, nil
}

// symbolLabel converts a symbol-db entry's label into an absolute label.
func symbolLabel(s plugin.TargetSymbol) label.Label {
	return label.Label{
		Repo:     s.Label.Repo,
		Pkg:      s.Label.Pkg,
		Name:     s.Label.Name,
		Relative: false,
	}
}

// importSpecsToTry yields one spec for ordinary imports, or `impt.Id` prefixed with `fromPkg`
// and each of its ancestors (ending with bare impt.Id at workspace root) for Ancestor imports.
func importSpecsToTry(impt plugin.TargetImport, fromPkg string) iter.Seq[resolve.ImportSpec] {
	return func(yield func(resolve.ImportSpec) bool) {
		if impt.Ancestor {
			for rel := fromPkg; rel != ""; {
				if !yield(resolve.ImportSpec{Lang: impt.Provider, Imp: rel + "/" + impt.Id}) {
					return
				}
				if i := strings.LastIndexByte(rel, '/'); i >= 0 {
					rel = rel[:i]
				} else {
					rel = ""
				}
			}
		}
		// Bare id: the only spec for non-ancestor imports, or the final step of the ancestor walk.
		yield(resolve.ImportSpec{Lang: impt.Provider, Imp: impt.Id})
	}
}

var _ resolve.CrossResolver = (*GazelleHost)(nil)

// Support imports from other gazelle extensions resolving to symbols provided by starzelle plugins.
func (ts *GazelleHost) CrossResolve(c *config.Config, ix *resolve.RuleIndex, imp resolve.ImportSpec, lang string) []resolve.FindResult {
	// Skip resolves from within this gazelle language, only support resolving from other languages
	if lang == GazelleLanguageName {
		return nil
	}

	// Search for results within this gazelle language, without further invoking CrossResolve
	// via FindRulesByImportWithConfig.
	return ix.FindRulesByImport(imp, GazelleLanguageName)
}

// targetListFromResults returns a string with the human-readable list of
// targets contained in the given results.
// TODO: move to gazelle/common
func targetListFromResults(results []resolve.FindResult) string {
	list := make([]string, len(results))
	for i, result := range results {
		list[i] = result.Label.String()
	}
	return strings.Join(list, ", ")
}
