"""
Aspect enhanced Gazelle
"""

load("//:rules.bzl", "aspect_gazelle_runner")

# The aspect_gazelle() default language set. The first three entries mirror
# upstream bazel-gazelle's DEFAULT_LANGUAGES; the rest are aspect-runner
# additions. Order matters — it affects resolution precedence.
DEFAULT_LANGUAGES = [
    # Upstream bazel-gazelle defaults:
    # https://github.com/bazel-contrib/bazel-gazelle/blob/v0.50.0/def.bzl#L59-L63
    "visibility_extension",
    "proto",
    "go",

    # Aspect-runner additions.
    "starlark",
    "python",
    "js",
]

# Keep in sync with the switch statement in runner/runner.go AddLanguage()
_VALID_LANGUAGES = [
    "buf",
    "cc",
    "go",
    "js",
    "kotlin",
    "orion",
    "proto",
    "python",
    "starlark",
    "visibility_extension",
]

def aspect_gazelle(
        name = "gazelle",
        languages = DEFAULT_LANGUAGES,
        extensions = [],
        extra_args = [],
        with_check = False,
        **kwargs):
    """Creates a Gazelle target for BUILD generation.

    Several well-supported languages are built into the prebuilt binary. The
    `languages` argument selects which to enable and defaults to `DEFAULT_LANGUAGES`
    — the aspect_gazelle default set, which is broader than upstream bazel-gazelle's
    `DEFAULT_LANGUAGES` (it adds starlark, python, and js on top of visibility, proto,
    and go). Pass an explicit list to narrow or replace it.

    Aspect Orion extensions are Starlark-based plugins that provide additional BUILD
    file generation capabilities beyond the standard language extensions. These can be
    added via the `extensions` argument.

    When the Go language is enabled, you must supply `repo_config` pointing at a file
    containing `go_repository` declarations for the modules Gazelle should resolve
    (typically `@bazel_gazelle_go_repository_config//:WORKSPACE`, generated by the
    `go_deps` extension). Without it, Gazelle's Go resolver falls back to network
    lookups against the Go module proxy for every unknown import and appears to hang.

    The underlying `gazelle()` binary and the `mode` attribute are managed by this
    macro and cannot be overridden: the main target runs in `mode = "fix"`, and the
    optional `.check` target (see `with_check`) runs in `mode = "diff"`.

    Example:
        ```starlark
        load("@aspect_gazelle_runner//:def.bzl", "aspect_gazelle")

        # Default name "gazelle", only "js" language, plus a `:gazelle.check` target for CI.
        aspect_gazelle(languages = ["js"], with_check = True)

        # Enable only specific languages
        # repo_config is required because Go is enabled; pass None to opt out
        # if your repo has no external Go dependencies.
        aspect_gazelle(
            name = "gazelle_go_proto",
            languages = ["go", "proto"],
            repo_config = "@bazel_gazelle_go_repository_config//:WORKSPACE",
        )

        # Add Orion extensions for custom generation
        aspect_gazelle(
            name = "gazelle_with_orion",
            languages = ["starlark"],
            extensions = ["//tools/gazelle:my_extension.axl"],
        )
        ```

    Args:
        name: Name of the target. Defaults to "gazelle".
        languages: A list of Gazelle language string keys to enable. Defaults to
            `DEFAULT_LANGUAGES`. Order matters — it affects resolution precedence.
            Example: `["go", "proto", "python"]`.
        extensions: A list of labels pointing to Aspect Gazelle Orion Starlark extensions
            to load. These extensions provide additional BUILD file generation logic.
        extra_args: Additional command-line arguments passed to Gazelle.
        with_check: If True, also creates a `<name>.check` target that runs Gazelle in
            `diff` mode, suitable for CI to verify BUILD files are up to date.
        **kwargs: Standard Bazel rule attributes (e.g. `visibility`, `testonly`).
    """

    if not languages and not extensions:
        fail("aspect_gazelle(name = %r): 'languages' and 'extensions' cannot both be empty. " % name +
             "Omit 'languages' to use DEFAULT_LANGUAGES, pass an explicit list, or supply " +
             "'extensions' to run orion-only.")

    for lang in languages:
        if lang not in _VALID_LANGUAGES:
            fail("Invalid language %r in 'languages'. Valid languages are: %s" % (lang, ", ".join(_VALID_LANGUAGES)))

    # Presence check must precede pop(): passing repo_config = None is a deliberate
    # opt-out (no external Go deps), distinct from omitting the argument entirely.
    if "go" in languages and "repo_config" not in kwargs:
        fail(
            "aspect_gazelle(name = %r): repo_config is required when 'go' is in languages. " % name +
            "Without it, Gazelle's Go resolver falls back to network lookups for every unknown " +
            "import and appears to hang. Pass " +
            "repo_config = \"@bazel_gazelle_go_repository_config//:WORKSPACE\" (generated by the " +
            "go_deps module extension), and add use_repo(go_deps, \"bazel_gazelle_go_repository_config\") " +
            "to your MODULE.bazel. Pass repo_config = None to opt out if you have no external Go deps.",
        )

    command = kwargs.pop("command", "update")
    if command not in ("update", "fix"):
        fail("Invalid 'command' %r. Must be one of: \"update\", \"fix\"." % command)

    common = dict(
        command = command,
        extra_args = extra_args,
        env = kwargs.pop("env", {}) | {
            "ENABLE_LANGUAGES": ",".join(languages if languages else ["orion"]),
            "ORION_EXTENSIONS": ",".join(["$(rootpath %s)" % p for p in extensions]),
        },
        data = kwargs.pop("data", []) + extensions,
        tags = kwargs.pop("tags", []) + ["manual", "supports_incremental_build_protocol"],
        repo_config = kwargs.pop("repo_config", None),
    )
    if "visibility" in kwargs:
        common["visibility"] = kwargs.pop("visibility")
    if "testonly" in kwargs:
        common["testonly"] = kwargs.pop("testonly")

    if kwargs:
        fail("aspect_gazelle() got unexpected keyword argument(s): %s" % ", ".join(kwargs.keys()))

    aspect_gazelle_runner(
        name = name,
        mode = "fix",
        **common
    )

    if with_check:
        aspect_gazelle_runner(
            name = name + ".check",
            mode = "diff",
            **common
        )
