name: Test
# Controls when the action will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
concurrency:
  # Cancel previous actions from the same PR or branch except 'main' branch.
  # See https://docs.github.com/en/actions/using-jobs/using-concurrency and https://docs.github.com/en/actions/learn-github-actions/contexts for more info.
  group: concurrency-group::${{ github.workflow }}::${{ github.event.pull_request.number > 0 && format('pr-{0}', github.event.pull_request.number) || github.ref_name }}${{ github.ref_name == 'main' && format('::{0}', github.run_id) || ''}}
  cancel-in-progress: ${{ github.ref_name != 'main' }}
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      # Checks-out your repository under github.workspace, so your job can access it
      - uses: actions/checkout@v5
      - name: Mount bazel caches
        uses: actions/cache@v4
        with:
          # Cache the --dist_cache and --repository_cache directories (see ci.bazelrc)
          # and the default bazel output (https://bazel.build/remote/output-directories#layout)
          # and bazelisk cache.
          path: |
            ~/.cache/bazel-disk-cache
            ~/.cache/bazel-repository-cache
            ~/.cache/bazel
            ~/.cache/bazelisk
          key: >-
            bazel-cache-${{ hashFiles('.bazelrc', '.bazelversion', '.bazeliskrc', 'MODULE.bazel') }}
          restore-keys: |
            bazel-cache-
      - name: bazel test //...
        shell: bash
        run: |
          bazel \
            --bazelrc=${GITHUB_WORKSPACE//\\/\/}/.github/workflows/ci.bazelrc \
            test \
            --config=local \
            //...
