name: Publish to BCR
on:
  workflow_call:
    inputs:
      tag_name:
        required: true
        type: string
      tag_prefix:
        required: true
        type: string
    secrets:
      BCR_PUBLISH_TOKEN:
        required: true
  workflow_dispatch:
    inputs:
      tag_name:
        required: true
        type: string
      tag_prefix:
        required: true
        type: string
jobs:
  publish:
    uses: bazel-contrib/publish-to-bcr/.github/workflows/publish.yaml@v1.2.0
    with:
      tag_name: ${{ inputs.tag_name }}
      tag_prefix: ${{ inputs.tag_prefix }}
      registry_fork: "aspect-build/bazel-central-registry"
      draft: false
    permissions:
      attestations: write
      contents: write
      id-token: write
    secrets:
      publish_token: ${{ secrets.BCR_PUBLISH_TOKEN }}
